/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.packtpub.alumni

import io.ktor.application.*
import io.ktor.features.ContentNegotiation
import io.ktor.gson.gson
import io.ktor.response.*
import io.ktor.routing.*

fun Application.alumniModule() {
    install(ContentNegotiation) {
        gson {
        }
    }
    routing {
        get("/") {
            call.respondText("Hello World")
        }
    }
}
