/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.packtpub.alumni

import io.ktor.application.call
import io.ktor.application.install
import io.ktor.features.ContentNegotiation
import io.ktor.gson.gson
import io.ktor.http.ContentType
import io.ktor.response.respond
import io.ktor.response.respondText
import io.ktor.routing.get
import io.ktor.routing.routing
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

data class Hello(val from: String, val to: String)

fun main(args: Array<String>) {
    val server = embeddedServer(Netty, port = 8080) {
        install(ContentNegotiation) {
            gson {
                setPrettyPrinting()
            }
        }
        routing {
            get("/") {
                call.respondText("Hello World!", ContentType.Text.Plain)
            }
            get("/hello") {
                val respond = Hello(from = "Jasoet", to = "The World!")
                call.respond(respond)
            }
        }
    }
    server.start(wait = false)
}
